syntax = "proto3";

package com.ppb.gamestate.api.outbound.fixture;

import "google/protobuf/timestamp.proto";

import "game_state_api_outbound_sport_soccer.proto";
import "game_state_api_outbound_sport_tennis.proto";
import "game_state_api_outbound_common.proto";

message Fixture {

    string sports_book_id = 1;
    google.protobuf.Timestamp expected_start_time = 2;
    google.protobuf.Timestamp expected_end_time = 3;
    google.protobuf.Timestamp actual_start_time = 4;
    FixtureStatus status = 5;
    FixtureGroup group = 6;
    FixtureAttributes attributes = 7;
    repeated com.ppb.gamestate.api.outbound.common.ExternalRef external_ref = 8;

    enum FixtureStatus {
        PRE_MATCH = 0;
        IN_RUNNING = 1;
        FINISHED = 2;
    }

    message FixtureGroup {
        string id = 1;
        string description = 2;
        repeated com.ppb.gamestate.api.outbound.common.ExternalRef external_ref = 3;
    }

    message FixtureAttributes {
        oneof sport_attributes {
            com.ppb.gamestate.api.outbound.sport.soccer.SoccerAttributes soccer_attributes = 1;
            com.ppb.gamestate.api.outbound.sport.tennis.TennisAttributes tennis_attributes = 2;
        }
    }
}
